AWSTemplateFormatVersion: '2010-09-09'
Transform: AWS::Serverless-2016-10-31
Description: AWS Serverless Spring Boot API - Users Service

Parameters:
  DBHost:
    Type: String
    Description: RDS Hostname
  DBPort:
    Type: String
    Default: "5432"
    Description: RDS Port
  DBName:
    Type: String
    Description: Database name
  DBUser:
    Type: String
    Description: Database username
  DBPassword:
    Type: String
    Description: Database password

Globals:
  Api:
    EndpointConfiguration: REGIONAL

Resources:
  ConiungoJavaLambdaTemplateFunction:
    Type: AWS::Serverless::Function
    Properties:
      Handler: com.coniungo.template.StreamLambdaHandler::handleRequest
      Runtime: java21
      CodeUri: .
      MemorySize: 512
      Policies: AWSLambdaBasicExecutionRole
      Timeout: 30
      Environment:
        Variables:
          DB_HOST: !Ref DBHost
          DB_PORT: !Ref DBPort
          DB_NAME: !Ref DBName
          DB_USER: !Ref DBUser
          DB_PASSWORD: !Ref DBPassword
      Events:
        ProxyResource:
          Type: Api
          Properties:
            Path: /{proxy+}
            Method: ANY

Outputs:
  ConiungoJavaLambdaTemplateServiceApi:
    Description: URL for Users API
    Value: !Sub 'https://${ServerlessRestApi}.execute-api.${AWS::Region}.amazonaws.com/Prod'
    Export:
      Name: ConiungoJavaLambdaTemplateServiceApiUrl
